services:
  api-gateway:
    build: ./api_gateway
    ports:
      - "8000:8000"
    depends_on:
      auth-service:
        condition: service_healthy
      chat-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      retries: 5
      start_period: 5s

  auth-service:
    build: ./auth_service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=mysql+pymysql://root:password@auth-db:3306/auth_db
    depends_on:
      auth-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 5s
      retries: 5
      start_period: 5s

  chat-service:
    build: ./chat_service
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=mysql+pymysql://root:password@chat-db:3306/chat_db
    depends_on:
      chat-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 5s
      retries: 5
      start_period: 5s

  auth-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: auth_db
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5
      start_period: 5s

  chat-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chat_db
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5
      start_period: 5s
  # --- Test Databases ---
  auth-test-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: auth_test_db
    ports:
      - "3310:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5
      start_period: 5s

  chat-test-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chat_test_db
    ports:
      - "3311:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5
      start_period: 5s
      
  frontend:
    build: ./chat-frontend
    ports:
      - "3000:3000"
    depends_on:
      api-gateway:
        condition: service_healthy
